// Core/Inc/app_config.h
#pragma once
#include "main.h"   // brings in HAL + type defs

// Map to the handles generated by CubeMX
#define APP_I2C_IMU   hi2c1
#define APP_UART_GPS  huart2
#define APP_UART_DBG  huart3

// IMU I2C 7-bit address (change if your IMU differs)
#define IMU_ADDR_7BIT (0x68)

// Make the handles visible to other translation units
extern I2C_HandleTypeDef APP_I2C_IMU;   // expands to: extern I2C_HandleTypeDef hi2c1;
extern UART_HandleTypeDef APP_UART_GPS; // expands to: extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef APP_UART_DBG; // expands to: extern UART_HandleTypeDef huart3;
